//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_BRANCH
    {
        public string FACT_NO { get; set; }
        public string BRANCH_NO { get; set; }
        public string BRANCH_NAME { get; set; }
        public string BRANCH_CN { get; set; }
        public Nullable<bool> IS_ACT { get; set; }
        public string DO_USER { get; set; }
        public string DO_TIME { get; set; }
    
        public virtual EM_FACT EM_FACT { get; set; }
    }
}
