//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_COMP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EM_COMP()
        {
            this.EM_FACT = new HashSet<EM_FACT>();
        }
    
        public string COMP_NO { get; set; }
        public string COMP_NAME { get; set; }
        public string COMP_CN { get; set; }
        public string INV_ADD { get; set; }
        public string COMP_BOSS { get; set; }
        public string COMP_TEL { get; set; }
        public string COMP_FAX { get; set; }
        public string COMP_MAIL { get; set; }
        public Nullable<bool> IS_ACT { get; set; }
        public string DO_TIME { get; set; }
        public string DO_USER { get; set; }
        public string COMP_INV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EM_FACT> EM_FACT { get; set; }
    }
}
