//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_FACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EM_FACT()
        {
            this.EM_BRANCH = new HashSet<EM_BRANCH>();
        }
    
        public string COMP_NO { get; set; }
        public string FACT_NO { get; set; }
        public string FACT_NAME { get; set; }
        public string FACT_CN { get; set; }
        public Nullable<bool> IS_ACT { get; set; }
        public Nullable<int> FACT_TYPE { get; set; }
        public string DO_TIME { get; set; }
        public string DO_USER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EM_BRANCH> EM_BRANCH { get; set; }
        public virtual EM_COMP EM_COMP { get; set; }
    }
}
