CREATE DATABASE HRPLO
GO
USE HRPLO 
CREATE TABLE USERS
(
	USER_NO	NVARCHAR(50) PRIMARY KEY,
	USER_NAME	NVARCHAR(50),
	USER_PASS	NVARCHAR(50),
	PRI_SEE	BIT,
	PRI_CRE	BIT,
	PRI_EDT	BIT,
	PRI_DEL	BIT,
	PRI_IMP	BIT,
	PRI_EXP	BIT,
	LOGIN_TIME	NVARCHAR(50),
	DO_USERS	NVARCHAR(50),
	DO_TIME	NVARCHAR(50),
	IS_ACT	BIT

)
GO
CREATE TABLE USER_GROUP		
(
	UG_NO	NVARCHAR(50) PRIMARY KEY,
	UG_NAME	NVARCHAR(50),
	PRI_SEE	BIT,
	PRI_CRE	BIT,
	PRI_EDT	BIT,
	PRI_DEL	BIT,
	PRI_IMP	BIT,
	PRI_EXP	BIT,
	DO_USERS	NVARCHAR(50),
	DO_TIME	NVARCHAR(50),
	IS_ACT	BIT
)