CREATE DATABASE HRPLO
GO
USE HRPLO 
CREATE TABLE USERS
(
	USER_NO	NVARCHAR(50) PRIMARY KEY,
	USER_NAME	NVARCHAR(50),
	USER_PASS	NVARCHAR(50),
	PRI_SEE	BIT,
	PRI_CRE	BIT,
	PRI_EDT	BIT,
	PRI_DEL	BIT,
	PRI_IMP	BIT,
	PRI_EXP	BIT,
	LOGIN_TIME	NVARCHAR(50),
	DO_USERS	NVARCHAR(50),
	DO_TIME	NVARCHAR(50),
	IS_ACT	BIT,
	LOGIN_FALSE INT
)
GO
CREATE TABLE USER_GROUP		
(
	UG_NO	NVARCHAR(50) PRIMARY KEY,
	UG_NAME	NVARCHAR(50),
	PRI_SEE	BIT,
	PRI_CRE	BIT,
	PRI_EDT	BIT,
	PRI_DEL	BIT,
	PRI_IMP	BIT,
	PRI_EXP	BIT,
	DO_USERS	NVARCHAR(50),
	DO_TIME	NVARCHAR(50),
	IS_ACT	BIT,
	USER_NO	NVARCHAR(50)
)
GO
CREATE TABLE EM_COMP
(
	COMP_NO	NVARCHAR(50) PRIMARY KEY,
	COMP_NAME	NVARCHAR(150),
	COMP_CN	NVARCHAR(150),
	INV_ADD	NVARCHAR(150),
	COMP_BOSS	NVARCHAR(150),
	COMP_TEL	NVARCHAR(150),
	COMP_FAX	NVARCHAR(150),
	COMP_MAIL	NVARCHAR(150),
	IS_ACT	BIT,
	DO_TIME	NVARCHAR(150),
	DO_USER	NVARCHAR(50)
)
GO
CREATE TABLE EM_FACT
(
	COMP_NO	NVARCHAR(50) ,
	FACT_NO	NVARCHAR(50) PRIMARY KEY,
	FACT_NAME	NVARCHAR(150),
	FACT_CN	NVARCHAR(150),
	IS_ACT	BIT,
	FACT_TYPE	INT,
	DO_TIME	NVARCHAR(150),
	DO_USER	NVARCHAR(50)
)
GO
CREATE TABLE EM_BRANCH
(
	FACT_NO	NVARCHAR(50),
	BRANCH_NO	NVARCHAR(50) PRIMARY KEY,
	BRANCH_NAME	NVARCHAR(150),
	BRANCH_CN	NVARCHAR(150),
	IS_ACT	BIT,
	DO_USER	NVARCHAR(150),
	DO_TIME	NVARCHAR(50),
)
