//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPLO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRPLO.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Infomation.
        /// </summary>
        public static string Basic_Info {
            get {
                return ResourceManager.GetString("Basic_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Boss.
        /// </summary>
        public static string Comp_Boss {
            get {
                return ResourceManager.GetString("Comp_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company China Name.
        /// </summary>
        public static string Comp_CN {
            get {
                return ResourceManager.GetString("Comp_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Fax.
        /// </summary>
        public static string Comp_Fax {
            get {
                return ResourceManager.GetString("Comp_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Infomation.
        /// </summary>
        public static string Comp_Info {
            get {
                return ResourceManager.GetString("Comp_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string Comp_INV {
            get {
                return ResourceManager.GetString("Comp_INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Mail.
        /// </summary>
        public static string Comp_Mail {
            get {
                return ResourceManager.GetString("Comp_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Comp_Name {
            get {
                return ResourceManager.GetString("Comp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company No.
        /// </summary>
        public static string Comp_No {
            get {
                return ResourceManager.GetString("Comp_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Telephone.
        /// </summary>
        public static string Comp_Tel {
            get {
                return ResourceManager.GetString("Comp_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrualation! You are create success.
        /// </summary>
        public static string Create_Success {
            get {
                return ResourceManager.GetString("Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Time.
        /// </summary>
        public static string Do_Time {
            get {
                return ResourceManager.GetString("Do_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do User.
        /// </summary>
        public static string Do_User {
            get {
                return ResourceManager.GetString("Do_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Information.
        /// </summary>
        public static string Fact_Info {
            get {
                return ResourceManager.GetString("Fact_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Address.
        /// </summary>
        public static string INV_ADD {
            get {
                return ResourceManager.GetString("INV_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IS_ACT {
            get {
                return ResourceManager.GetString("IS_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Form.
        /// </summary>
        public static string Login_Form {
            get {
                return ResourceManager.GetString("Login_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
